name: Economy
version: '${1.0}'
main: me.gerald.economy.Main

commands:
  economy:
    aliases: [e]
    description: Default plugin header.
    default: true
permissions:
    economy.op:
      description: Operator on the server.
      default: op
